---
  tasks:
    - name: Add Portgroup with Promiscuous
      vmware_portgroup:
        hostname: '10.215.99.55'
        username: 'administrator@vsphere.local'
        password: 'Lab2021*'
        esxi_hostname: '10.215.99.60'
        switch_name: "vSwitch0"
        portgroup_name: 'PG45'
        vlan_id: '12'
        validate_certs: False
